path: /home/gbox3d/work/dataset/madang/madang_lts
train: yolov5/train
test: yolov5/test
val: yolov5/val

voc: voc/
img: voc/

split:  # define train/val set split ratio
  train : 0.7
  val : 0.1
  test : 0.2
  
nc: 14
names: 
- temper_sensor
- water_wheel_run
- water_wheel_stop
- water_bubble
- dight_0
- dight_1
- dight_2
- dight_3
- dight_4
- dight_5
- dight_6
- dight_7
- dight_8
- dight_9

voc_util_path : /home/gbox3d/work/visionApp/daisy_project/trainer/yolo_v5
trainer_path : /home/gbox3d/work/visionApp/Yolov5_DeepSort_Pytorch/yolov5